#!/usr/bin/env ruby

git_bundles = [ 
  "https://github.com/astashov/vim-ruby-debugger.git",
  "https://github.com/Lokaltog/vim-powerline.git",
  "https://github.com/msanders/snipmate.vim.git",
  "https://github.com/scrooloose/nerdtree.git",
  "https://github.com/timcharper/textile.vim.git",
  "https://github.com/tpope/vim-cucumber.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/tpope/vim-git.git",
  "https://github.com/tpope/vim-haml.git",
  "https://github.com/tpope/vim-markdown.git",
  "https://github.com/tpope/vim-rails.git",
  "https://github.com/tpope/vim-repeat.git",
  "https://github.com/tpope/vim-surround.git",
  "https://github.com/tpope/vim-vividchalk.git",
  "https://github.com/tsaleh/vim-align.git",
  "https://github.com/tsaleh/vim-shoulda.git",
  "https://github.com/ervandew/supertab.git",
  "https://github.com/tomtom/tcomment_vim.git",
  "https://github.com/vim-ruby/vim-ruby.git",
  "https://github.com/duskhacker/sweet-rspec-vim.git",
  "https://github.com/elixir-lang/vim-elixir.git",
  "https://github.com/kchmck/vim-coffee-script.git",
  "https://github.com/sunaku/vim-ruby-minitest.git",
  "https://github.com/tpope/vim-eunuch.git",
  "https://github.com/tpope/vim-rake.git",
  "https://github.com/godlygeek/tabular.git",
  "https://github.com/airblade/vim-rooter.git",
  "https://github.com/29decibel/codeschool-vim-theme.git",
  "https://github.com/tpope/vim-endwise.git",
  "https://github.com/greyblake/vim-preview.git",
  "https://github.com/ecomba/vim-ruby-refactoring.git",
  "https://github.com/vim-scripts/IndexedSearch.git",
  "https://github.com/vim-scripts/jQuery.git",
  "https://github.com/mileszs/apidock.vim.git",
  "https://github.com/vim-scripts/Gist.vim.git",
  "https://github.com/skwp/vim-rspec.git",
  "https://github.com/tsaleh/vim-matchit.git",
  "https://github.com/tpope/vim-commentary.git",
  "https://github.com/pangloss/vim-javascript.git",
  "https://github.com/postmodern/vim-yard.git",
  "https://github.com/vim-scripts/VimClojure.git",
  "https://github.com/vim-scripts/Vim-JDE.git",
  "https://github.com/derekwyatt/vim-scala.git",
  "https://github.com/jnwhiteh/vim-golang.git",
  "https://github.com/tpope/vim-rake",
  "https://github.com/airblade/vim-gitgutter.git"
]

vim_org_scripts = [
  ["Vimerl",	      "3743",	"syntax"],
  ["RailsCast",	      "2175",	"color"],
  ["BufferExplorer",  "42",	"plugin"],
  ["JSLint",	      "2729",	"plugin"]
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "*** Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

# download Github repos
git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

# download all vim scripts
unless /cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM
  vim_org_scripts.each do |name, script_id, script_type|
    puts "  Downloading #{name}"
    local_file = File.join(name, script_type, "#{name}.vim")
    FileUtils.mkdir_p(File.dirname(local_file))
    File.open(local_file, "w") do |file|
      file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
    end
  end
end
